---
- name: create prometheus system group
  group:
    name: prometheus
    system: true

- name: create prometheus system user
  user:
    name: prometheus
    system: true
    shell: '/usr/sbin/nologin'
    group: prometheus
    createhome: false
    home: '{{ prometheus_dir }}'

- name: create prometheus data directory
  file:
    path: '{{ item }}'
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0755
  with_items:
    - '{{ prometheus_dir }}'
    - '{{ prometheus_data_dir }}'

- name: Download and untar prometheus
  unarchive:
    src: '{{ download_url }}'
    dest: '{{ prometheus_dir }}'
    remote_src: yes
    owner: prometheus
    group: prometheus
    extra_opts:
    - --strip-components=1
    creates: '{{ prometheus_dir }}/prometheus'

- name: Create systemd service unit
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    mode: 0644
  notify:
    - restart prometheus

- name: Template prometheus.yml config file
  template:
    src: prometheus.yml.j2
    dest: '{{ prometheus_dir }}/prometheus.yml'
    owner: prometheus
    group: prometheus
    mode: 0640
  notify:
    - reload prometheus

- name: Ensure prometheus service is started and enabled
  systemd:
    daemon_reload: true
    name: prometheus
    state: started
    enabled: true
